---
title: "Proposal on F.R.I.E.N.D.S"
author:
  - name: "Manas P Panse"
    affiliations:
      - name: "iSchool, University of Arizona"
description: "An analysis of character dialogues, emotions, and episode metadata from the TV show Friends, aiming to uncover patterns in emotions, dialogue frequency, and relationships between characters across the seasons."
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
    code-fold: true
editor: source
code-annotations: hover
execute:
  warning: false
  message: false
  error: false
toc: true
---

# 1 - Introduction

This project aims to investigate and analyze key character emotions, interactions, and patterns in the iconic ***FRIENDS*** TV show using a variety of datasets. By understanding how emotions evolve over time and the interaction patterns of characters, we can uncover insights about character development and audience engagement.

# 2 - Workspace Setup

```{python}
#| label: workspace-setup
#| code-summary: Workspace Setup

# Importing Necessary Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Setting Plot Styles
sns.set_theme(style = "white")

# Importing Datasets
friends_df = pd.read_csv('data/friends.csv')
friends_emotions_df = pd.read_csv('data/friends_emotions.csv')
friends_info_df = pd.read_csv('data/friends_info.csv')
```

# 3 - Data

```{python}
#| label: friends-df-view
#| code-summary: Friends Info

# FRIENDS
friends_df.info()
```

```{python}
#| label: friends-emotions-view
#| code-summary: Friends-Emotions Info

# FRIENDS_EMOTIONS
friends_emotions_df.info()
```

```{python}
#| label: friends-info-view
#| code-summary: Friends-Info Info

# FRIENDS_INFO
friends_info_df.info()
```

###### FRIENDS

1.  Columns - `text`, `speaker`, `season`, `episode`, `scene`, `utterance`.
2.  Rows - 67373
3.  Info - This dataset contains EACH & EVERY line of dialogue that is spoken in the show, providing us with a rich database for analyzing chracter interactions & speech patterns.

###### FRIENDS_EMOTIONS

1.  Columns - `season`, `episode`, `scene`, `utterance`, `emotion`.
2.  Rows - 12606
3.  Info - This dataset provides an EMOTIONAL label for each line, allowing for an in - depth analysis of character emotions across episodes & seasons.

###### FRIENDS_INFO

1.  Columns - `season`, `episode`, `title`, `directed_by`, `written_by`, `air_data`, `us_views_millions`, `imdb_rating`.
2.  Rows - 236
3.  Info - This dataset is CRUCIAL for contextualizing the show's progression, viewership trends, and episode quality.

I have chosen these ***FRIENDS*** datasets because, well I love the show; which for me is the ONLY reason. But for a more professional reason, these datasets provide an incredibly detailed glimpse into one of the **MOST BELOVED** TV shows of all time.

As a massive fan, I am honestly interested about each of our ***FRIENDS*** development over time. This really might prove to be a treasure chest - containing insights into their emotions & personalities that have captivated the audience for decades (me personally few years).

Exploring this dataset is like 'breaking the 4th Wall' for me, discovering the emotional highs and lows, understanding some intricate bonds between our ***FRIENDS*** & even predicting how future episodes might unfold based on certain recurring factors.

# 4 - Questions

***Based on my analysis, questions have been altered.***

1.  How are IMDb rating trends and viewership trends for the show ?

2.  Which character dominates the dialogue in each EP and/or SS ?

3.  Which character uses the most positive or optimistic language throughout the series ?

# 5 - Analysis Plan

***Based on my analysis, the analysis plan has been altered.***

3.  IMDb Rating & Viewership Trends :
    1.  Variables Involved : `season`, `episode`, `us_views_millions`, `imdb_rating`.
    2.  Plan :
        -   Aggregate the IMDb ratings & viewership per season.
        -   Visualize results using line plots separately for IMDb ratings & viewership.

2.  Character Dominance Analysis :
    1.  Variables Involved : `speaker`, `season`, `episode`, `utterance`.
    2.  Plan :
        -   Group by `season`, `episode` to isolate counts within season AND `season`, `episode` to isolate dialogue counts within an episode.
        -   Aggregate `utterance` counts for each of the F.R.I.E.N.D.S to find the one with the most dialogue.
        -   Visualize results using bar plots.

3.  Language Usage :
    1.  Variables Involved : `season`, `episode`, `speaker`, `text`.
    2.  Model Development :
        -   This will be approached in two ways -
            -   For simplicity as our priority, utilizing the **TextBlob** model would prove beneficial.
            -   For complexity as our priority, utilizing the **BigBird** model would prove beneficial.
    3.  Plan :
        -   Perform sentimental analysis on the `text` field to evaluate the tone.
        -   Compare polarity scores by character
        -   Visualize results using donut plots.
        
# 6 - Possible Limitations

1.  The dataset `friends_emotions_df` has less rows than `friends_df`. This incompleteness in my data will cause some of the dialogues to not have an emotional label. This issue could possibly skew my analysis if these labels are utilized.

# 7 - Modus Operandi

***Based on my analysis, this has been altered.***

| **Task Name** | **Status** | **Due** | **Priority** | **Summary** |
|---|---|---|---|---|
| **Initial Research** | COMPLETE | 03-Nov-24 | HIGH | Outline project goals, research questions, and data sources centered on 90s TV sitcom *FRIENDS*. |
| **Project Proposal for Initial Review** | COMPLETE | 03-Nov-24 | HIGH | Submit the project proposal for initial instructor review, outlining the goals, research questions, and the plan of attack. |
| **Project Proposal for Final Review** | COMPLETE | 10-Nov-24 | HIGH | Amend the necessary changes suggested by the instructor to the `proposal.qmd`, and submit for final review. |
| **Abstract & Workspace Setup** | COMPLETE | 09-Dec-24 | HIGH | Summarize the project, along with the necessary datasets, and import necessary libraries and datasets into the environment. |
| **IMDb Ratings Trend** | COMPLETE | 09-Dec-24 | HIGH | Analyze the `friends_info.csv` dataset to aggregate IMDb ratings per season & plot the line graph to assess their growth or decline. |
| **Viewership Trend** | COMPLETE | 09-Dec-24 | HIGH | Analyze the `friends_info.csv` dataset to aggregate US viewership per season & plot a line graph to assess their growth or decline. |
| **Character Dominance** | COMPLETE | 09-Dec-24 | HIGH | Analyze the `friends.csv` dataset to identify the character who dominates dialogue in each season & episode. Aggregate the dialogue counts & the visualize interactive bar graphs separately for season & episode. |
| **Emotional Tone Analysis** | COMPLETE | 09-Dec-24 | HIGH | Perform sentiment analysis on the `friends.csv` dataset using *TextBlob* and *BigBird* and visualize the polarity of dialogues spoken by the main cast using donut charts. |
| **Website Update** | COMPLETE | 09-Dec-2024 | HIGH | Render the website for the last time. :) |
| **Final Commit & Push** | COMPLETE | 09-Dec-2024 | HIGH | Confirm all changes & submit the code for the last time. :) |